name: deploy-book
on:
  push:
    branches:
      - main

permissions:
  contents: write       # ✅ allows ghp-import to push to gh-pages
  pages: write          # ✅ required for GitHub Pages deployments
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install jupyter-book ghp-import

      - name: Build Jupyter Book
        run: jupyter-book build .

      - name: Deploy to GitHub Pages
        run: ghp-import -n -p -f _build/html
